### ISSUE TITLE
Не работает получение Сидов и Личей (LostFilm.TV)

### ISSUE THREAD

**Issue by AlexMak58** [bugsbringer/qbit-plugins#1]
Не работает получение Сидов и Личей на LostFilm.TV.

**Comment by bugsbringer** [comment]
Здравствуйте.
Следовали инструкциям в readme репозитория?
https://github.com/bugsbringer/qbit-plugins/blob/master/README.md

сб, 30 мая 2020 г. в 05:34, Александр <notifications@github.com>:

**Comment by AlexMak58** [comment]
Необходимые дополнительные модули установлены.
<details>
![image](https://user-images.githubusercontent.com/34411074/83334844-e9952c00-a2b1-11ea-9572-0f0396c5a611.png)
</details>

**Comment by bugsbringer** [comment]
Сложно даже представить в чем может быть проблема.
Если не затруднит, предлагаю провести поиск прямым вызовом скрипта из консоли:
python lostfilm.py breaking bad
И отправить скриншот с ошибкой в эту тему.
У меня пока 2 варианта: либо какая-то ошибка или зависимость которой я не замечаю, либо получение данных из торрент файла занимает слишком много времени. Хоть я и проводил тесты на ~600 результатов поиска, всё работало прекрасно.

**Comment by AlexMak58** [comment]
Я скачал модули из репозитория qBittorrent по Вашей ссылке, поместил скрипт lostfilm.py и необходимые модули в отдельную папку и запустил, но получил ошибку:
```
PS C:\Users\User\Downloads\Новая папка> python.exe .\lostfilm.py Breaking Bad
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 1319, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1004, in _send_output
    self.send(msg)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 944, in send
    self.connect()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1399, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\lostfilm.py", line 394, in <module>
    lf = lostfilm()
  File ".\lostfilm.py", line 51, in __init__
    self.session = Session()
  File ".\lostfilm.py", line 222, in __init__
    self.load_data()
  File ".\lostfilm.py", line 226, in load_data
    self.create_new()
  File ".\lostfilm.py", line 261, in create_new
    response = opener.open(url, params.encode('utf-8'))
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 1362, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 1322, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1108)>
```

**Comment by AlexMak58** [comment]
Проблема выше была решена включением средств обхода блокировок ([ReQrypt](https://github.com/basil00/reqrypt)).
Получаю вывод:
```
PS C:\Users\User\Downloads\Новая папка> python.exe .\lostfilm.py Breaking Bad
http://n.tracktor.site/td.php?s=y3FgRNcMY96K1XbznU3CfASqNaO6BQIxyEZwOEkRMVErtufHnz%2B9%2FRDsZKT7EPSn9s%2BBGz9tO7iB7aIio%2FDKT9wBLAjNF5mWmDY3E%2BBonMZ1dQiEZQcCvpfh7FCs%2B6FO|Во все тяжкие.  5 сезон. WEB-DLRip|8750995865|-1|-1|https://www.lostfilm.tv|https://www.lostfilm.tv/series/Breaking_Bad/season_5/episode_16/
http://n.tracktor.site/td.php?s=5ppdc%2B0AJ1Iv7ucqHX23XIYYj7Nr0ONwfFTUGkQKG5V10hf6yJm5FyHuXUJC7pujXGbLiecM7P%2BQLc6fk8Qti0N6vIbJVxW%2BlP2DtScCws1UnoNUGkJzvl7PuchCJP8Q|Во все тяжкие.  5 сезон. 720p WEB-DLRip|27444841021|-1|-1|https://www.lostfilm.tv|https://www.lostfilm.tv/series/Breaking_Bad/season_5/episode_16/
http://n.tracktor.site/td.php?s=9DFsTqys0iNYKWitJjwfbUhOUeWHhPFh6G%2F3I0BfGM9HgR5n6%2FEc01bOfNt1f7RZSzHOVkld6nzZbOZw9mfKTlD0fah1uAATyGWLmzldAco5upwPjnUqMvqhP4m7QD%2F7|Во все тяжкие.  4 сезон. WEB-DLRip|6882685091|-1|-1|https://www.lostfilm.tv|https://www.lostfilm.tv/series/Breaking_Bad/season_4
http://n.tracktor.site/td.php?s=Ae2UIXbxK%2B0rZ6YVJaQNnDzEgn4f9PQ0VUgqqwUYnYUB2turppchgdt25Bdv924QGxqw0IVX3p8GfWEvnrnZwi6j0vgrjSVzGQTH3TS2EaaDT3NeLmfOoIRdFlhMDaWx|Во все тяжкие.  4 сезон. 720p WEB-DLRip|20336670146|-1|-1|https://www.lostfilm.tv|https://www.lostfilm.tv/series/Breaking_Bad/season_4
http://n.tracktor.site/td.php?s=wBO30pQdIZlhqpgLq%2BNKIHlfXYZHPA%2F2kSZdbvlFDYLc%2F91aqN7r5Rl4ay03jQ%2B%2FE1NgTNw87MHAwtK%2BtaSUu%2BEoWaRWhI7LPCwMQ6yLgIcSnNX6Ju%2FWDWIlOfgJucxHd8GAgg%3D%3D|Во все тяжкие.  El Camino: Во все тяжкие.  WEB-DLRip|1911260446|-1|-1|https://www.lostfilm.tv|https://www.lostfilm.tv/series/Breaking_Bad/additional/episode_1/
http://n.tracktor.site/td.php?s=tKgVFbtVHZaijMQ0DlElN8TyrdLj6erjOw0JclUzbyEdHCcw5nmVU4R9PPTuPSlVncXZSCyul38Khd6MNjeOW7so1aYojFbsHCabv0pXZaezHqBwYkglDKM4x7UkQ1PZwQ2s%2FA%3D%3D|Во все тяжкие.  3 сезон. WEB-DLRip|9266391941|-1|-1|https://www.lostfilm.tv|https://www.lostfilm.tv/series/Breaking_Bad/season_3
http://n.tracktor.site/td.php?s=pXBlX0udK8%2BLHobWtjW4o5n%2Bu6bJsYQ4xWBPXqa%2FKiW9mgRRWHgC9spqzhJVhIUNwDiYsyhyBCUqlEEow5G2DDGwIhU4DFqeqhH2rkdcGuxSy8inZoDl4vZL6JzSUxd5YsapzA%3D%3D|Во все тяжкие.  El Camino: Во все тяжкие.  1080p WEB-DLRip|6968584437|-1|-1|https://www.lostfilm.tv|https://www.lostfilm.tv/series/Breaking_Bad/additional/episode_1/
http://n.tracktor.site/td.php?s=%2BGTTezMx223C5DCAPCanPYdPWWInpdLWzpdeKQ1CWGRGX4O6GHoECE3MgVN%2FrsaPZvFortRjYJEKnWw4eqpm6LCeDDyN6ssVPM%2B3VOED1Xg4SWF0Xe1zasY39zWZ5yesl4rMcQ%3D%3D|Во все тяжкие.  2 сезон. WEB-DLRip|9792525434|-1|-1|https://www.lostfilm.tv|https://www.lostfilm.tv/series/Breaking_Bad/season_2
http://n.tracktor.site/td.php?s=XyKc5yb%2FWLuReZ1vBZR7mEGnI5F3KOk9%2Fn7ZfnMNsXlZbzYjTQjXsRg0ZTVtyTG0zJ6F0MAPqvBBp2iy7wUDoYJvz2bsoMnH8DQEWm7eo4GLLIGKoN5wR3ka630Aa4PIcUvaYQ%3D%3D|Во все тяжкие.  1 сезон. WEB-DLRip|5443871047|-1|-1|https://www.lostfilm.tv|https://www.lostfilm.tv/series/Breaking_Bad/season_1
http://n.tracktor.site/td.php?s=BikHc027eEZicJLsr%2FQ4okeG4RXlQHXN5RVkaZ2JOurpJlnAiSoKSRaIJka830QMNppK9MWz4KRSHpur9SxH2y7mcEq795W5ZyjD1tyrxiPgxIaPzvNg8F5VNwmGkYnPTyNgZQ%3D%3D|Во все тяжкие.  El Camino: Во все тяжкие.  720p WEB-DLRip|3919157657|-1|-1|https://www.lostfilm.tv|https://www.lostfilm.tv/series/Breaking_Bad/additional/episode_1/
http://n.tracktor.site/td.php?s=w7jDbWw7nwW7%2FVSjOOfS5YL3z%2F6vY01WbU6b%2BeOPRFf71zKtvmlBPn5ImVvjKEv9iRjXZ0%2FFZUDFUs8hr2c%2B2HWd93qxbgFJi9B6UTji5VITHWctMA3qhZp0zT3M%2Fo%2BDPFtuew%3D%3D|Во все тяжкие.  2 сезон. 1080p WEB-DLRip|35046933135|-1|-1|https://www.lostfilm.tv|https://www.lostfilm.tv/series/Breaking_Bad/season_2
http://n.tracktor.site/td.php?s=0Eb9cqXsTBKFQhWm3gbc4eoMr0YBBx3dUBvQxalcURPooNagJnu6sW%2BuHZLYUPOKSG8tQ%2F%2Bq5WdtJrUK83Lsv35oyVz74ZiQSTw77dn8FOjqI8L%2FTGXzKQ7vNysZZcWftz2TXA%3D%3D|Во все тяжкие.  3 сезон. 1080p WEB-DLRip|34961033789|-1|-1|https://www.lostfilm.tv|https://www.lostfilm.tv/series/Breaking_Bad/season_3
http://n.tracktor.site/td.php?s=FsM%2FhGPANMGWqdWSc3SqB5NReMhZwZgbXPd5iben%2FSXqu22Fze8RjVBricZa8u0XnAr7eWyWQ5EEWny%2BzWBCzPA9XCe4DnmsjmjVRoGggplWd%2FlAEQ7YYZVQg7VBcQkHc4p0Vw%3D%3D|Во все тяжкие.  1 сезон. 1080p WEB-DLRip|19735374725|-1|-1|https://www.lostfilm.tv|https://www.lostfilm.tv/series/Breaking_Bad/season_1
http://n.tracktor.site/td.php?s=L1DUaQrSLAaXY1kzQxG9aws7swS9DTQ4jh%2FgR9B2QzNFafiVQ0eWvXAtq7%2FOKBq3Ipr7yC80Zm1ckxsQ9bHfApXM0XaBmc%2BpEyopjiJ%2BygUFIzNBgJwmhoUkkJPNSh%2F8DHeJRw%3D%3D|Во все тяжкие.  1 сезон. 720p WEB-DLRip|11005853696|-1|-1|https://www.lostfilm.tv|https://www.lostfilm.tv/series/Breaking_Bad/season_1
http://n.tracktor.site/td.php?s=aatmfmEo7l1N0khFRnACQzQpC%2F7%2BiOJTDp2WV8ZTYbxliRxUpdBGCoguovwU%2FoVzif7FMPOFtQP080fCj71ay05hPP26Ib2eZZKz13SoUyLij2%2Bon11KZ9Nwft9v6O4Yp3aWiQ%3D%3D|Во все тяжкие.  2 сезон. 720p WEB-DLRip|19563576033|-1|-1|https://www.lostfilm.tv|https://www.lostfilm.tv/series/Breaking_Bad/season_2
http://n.tracktor.site/td.php?s=GlOHRDKRpvK4zAxgAQblEPKFHItsUd66HPuCHBJbtqg8%2B%2B9OiRHYOXZndxpVaZMSK%2BCuTGkIhWIaAt3OwIejS6RWkMIlDrFkj83PNmq7%2Btf8%2BOELxieYH%2FM4ImumXVmcFRqgfA%3D%3D|Во все тяжкие.  3 сезон. 720p WEB-DLRip|19499151523|-1|-1|https://www.lostfilm.tv|https://www.lostfilm.tv/series/Breaking_Bad/season_3
```

**Comment by AlexMak58** [comment]
Примечательно, что даже через [Jackett](https://github.com/Jackett/Jackett) я не получаю Сиды и Личи.
![image](https://user-images.githubusercontent.com/34411074/83340675-c84d3380-a2e3-11ea-9b9c-ce8acfdddfc0.png)

**Comment by bugsbringer** [comment]
Это нормальное поведение для Jackett, в нём просто не реализовано получение этой информации из торрент файла.
![image](https://user-images.githubusercontent.com/43088564/83340744-a1433180-a2e4-11ea-8ed8-846a5f385b1b.png)

**Comment by AlexMak58** [comment]
Окей, и как же получить лог? Есть ли какой-нибудь флажок `--debug` или `--verbose`?
Да, я дождался завершения скрипты, он просто завершается без какого-либо вывода.
![image](https://user-images.githubusercontent.com/34411074/83340817-5675e980-a2e5-11ea-8703-9a999bac8a56.png)

**Comment by bugsbringer** [comment]
Такую функцию не реализовывал, будет над чем поработать.
Сожалею, что не смог помочь.
Есть ещё вариант, но это мало вероятно:
можете попробовать заменить 169 строку кода на:
torrent = bencode.bdecode(requests.get(tdict['link'], verify=False).content)

**Comment by AlexMak58** [comment]
Попробовал изменить 169-ю строчку кода на Вашу, но ничего не изменилось.
С включенным обходом блокировок все также нет никакого вывода, а с выключенным вообще не могу получить доступ к сайту и получаю ошибку проверки сертификата (у моего провайдера подмена SSL-сертификата).
![image](https://user-images.githubusercontent.com/34411074/83340966-e1a3af00-a2e6-11ea-8466-f36f92b54a82.png)

**Comment by bugsbringer** [comment]
Здравствуйте, 
изменилась ли ситуация с получением пиров?
